defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/project

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: echo "Dummy - moved to github"